### PR TITLE
Start script fixes

### LINKED ISSUE #89: Startup scripts run again on instance restart
When an instance is resumed on GCP the startup scripts run again. Which means the `buttons-start` script will run for a second time on the instance, potentially wiping out changes made since it is re-importing the app/data with `overwrite` set as the import policy. Example. If one of the preexisting pipelines is changed and not renamed and subsequent import will revert the changes made on restart.

Looks like some space was commented out in the `start-button.sh` script (line 127) to have some conditionals on whether an app has been installed yet to prevent this. 

Currently it checks to see if Fusion is already installed and does something else if it is. This same logic needs to apply to the DISTRO if it has already been installed.

### PR DESCRIPTION
**Pull request by sudosoup**
Fixes #89 

Added conditional to check for "$SID" directory at root which is created on first spinup.

If directory does NOT exist: proceed as usual with exporting vars and executing buttons-start script

If directory does exist: echo "This demo is already installed" and skip running the buttons-start script. 

Tested on dev environment of labs, looks to be working.

Final thoughts: seems to be a good fix to avoid reimporting a demo and wiping changes. Can still possibly happen if the demo dir is wiped out or changed.

### CODE REVIEW

File: projects/buttons/fastener/scripts/start-button.sh [hunk 1]
```diff
@@ -120,17 +120,29 @@ fi
...
 
-# TODO: conditional on DISTRO: fetch if specified, otherwise ignore
-#   - if no DISTRO to fetch, then this becomes a simple Fusion out of the box, box
-
+#copy demo data from bucket and unzip
 gsutil cp gs://buttons-streams/$DISTRO .
 tar xfz $DISTRO
 
 # check for existence (and executable-ness) of ./buttons-start.sh
 export FUSION_API_BASE; export FUSION_API_CREDENTIALS; export ADMIN_PASSWORD; export IP; ./buttons-start.sh
```
Comment (MarcusSorealheis) [inline projects/buttons/fastener/scripts/start-button.sh]: It looks like there is an errant space, is that true? Maybe it's just the indent in the browser.

Comment (sudosoup) [reply projects/buttons/fastener/scripts/start-button.sh]: Think it is just the browser wrapping the line.

**Comment by MarcusSorealheis** [comment]
@sudosoup Don't think you should delete branches. Also, did you see my comment above before you merged?
